Feature list_auto_scale_vm_groups for list Autoscaling
StackStorm-Exchange/stackstorm-cloudstack pull request #4
Opened 2019-10-09 21:49 UTC by Nicodemos305

Add feature list_auto_scale_vm_groups for list autoscaling of lb.

2019-10-09 21:50 UTC, Nicodemos305 commented
Pull request of issue #3

2019-10-10 12:06 UTC, arm4b requested changes

2019-10-10 12:06 UTC, armab commented on CHANGES.md
> +## 0.5.16
```suggestion
## 0.6.0
```

Per https://semver.org/ if new functionality was added minor version should be incremented.
Patch version is for fixes.

2019-10-10 12:06 UTC, armab commented on pack.yaml
> +version: 0.5.16
```suggestion
version: 0.6.0
```

2019-10-10 14:34 UTC, armab commented on CHANGES.md
> +## 0.5.16
Can you include this change as well?

2019-10-10 15:17 UTC, arm4b approved these changes
LGTM :+1:

2019-10-10 17:10 UTC, merged